language: php

php:
  - 7.1

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate

script:
  - phpunit

notifications:
  email: false
